CREATE USER readonlyuser WITH ENCRYPTED PASSWORD '485read99cd01';
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonlyuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonlyuser;
